// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injectors

import (
	"context"
	"github.com/wt5858/trading-agents-go/config"
	http_handlers3 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/agent/application/http_handlers"
	domain_services2 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/agent/domain_services"
	repositories3 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/agent/repositories"
	amqp_handlers2 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/analysis/application/amqp_handlers"
	domain_event_handlers3 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/analysis/application/domain_event_handlers"
	http_handlers4 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/analysis/application/http_handlers"
	"github.com/wt5858/trading-agents-go/internal/bounded_contexts/analysis/application/mcp_tools"
	domain_services3 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/analysis/domain_services"
	repositories2 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/analysis/repositories"
	"github.com/wt5858/trading-agents-go/internal/bounded_contexts/identity/application/http_handlers"
	"github.com/wt5858/trading-agents-go/internal/bounded_contexts/identity/domain_services"
	"github.com/wt5858/trading-agents-go/internal/bounded_contexts/identity/repositories"
	"github.com/wt5858/trading-agents-go/internal/bounded_contexts/notification/application/domain_event_handlers"
	http_handlers10 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/notification/application/http_handlers"
	domain_services10 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/notification/domain_services"
	repositories11 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/notification/repositories"
	http_handlers9 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/paper_trading/application/http_handlers"
	domain_services9 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/paper_trading/domain_services"
	repositories10 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/paper_trading/repositories"
	domain_event_handlers2 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/report/application/domain_event_handlers"
	http_handlers5 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/report/application/http_handlers"
	domain_services8 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/report/domain_services"
	repositories8 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/report/repositories"
	"github.com/wt5858/trading-agents-go/internal/bounded_contexts/scheduling/application/amqp_handlers"
	http_handlers6 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/scheduling/application/http_handlers"
	repositories9 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/scheduling/repositories"
	http_handlers11 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/screening/application/http_handlers"
	mcp_tools3 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/screening/application/mcp_tools"
	domain_services5 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/screening/domain_services"
	repositories6 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/screening/repositories"
	http_handlers2 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/stock/application/http_handlers"
	domain_services6 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/stock/domain_services"
	repositories5 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/stock/repositories"
	http_handlers7 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/system_config/application/http_handlers"
	domain_services7 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/system_config/domain_services"
	repositories7 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/system_config/repositories"
	http_handlers8 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/watchlist/application/http_handlers"
	mcp_tools2 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/watchlist/application/mcp_tools"
	domain_services4 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/watchlist/domain_services"
	repositories4 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/watchlist/repositories"
	"github.com/wt5858/trading-agents-go/internal/di/providers"
	"github.com/wt5858/trading-agents-go/internal/helpers/event_handlers"
	"github.com/wt5858/trading-agents-go/internal/mcpserver"
	"github.com/wt5858/trading-agents-go/internal/server"
	"go.uber.org/zap"
)

// Injectors from container.go:

// CreateHTTPServer 装配 HTTP 服务。
//
// 它需要几乎全部上下文的领域服务（接口要暴露它们），但**不包含任何消费者**。
func CreateHTTPServer(ctx context.Context, cfg *config.Config, log *zap.Logger) (*server.Server, error) {
	connections, err := providers.NewSingletonConnections(ctx, cfg, log)
	if err != nil {
		return nil, err
	}
	db := providers.NewGormDB(connections)
	userRepository := repositories.NewUserRepository(db)
	client := providers.NewRedisClient(connections)
	sessionRepository := providers.NewSessionRepository(client, cfg)
	issuer := providers.NewTokenIssuer(cfg)
	bcryptHasher := providers.NewPasswordHasher(cfg)
	amqp, err := providers.NewSingletonAmqp(cfg, log)
	if err != nil {
		return nil, err
	}
	amqpBus := providers.NewDomainEventBus(amqp, log)
	authService := domain_services.NewAuthService(userRepository, sessionRepository, issuer, bcryptHasher, amqpBus)
	taskRepository := repositories2.NewTaskRepository(db)
	taskDispatcher := providers.NewTaskDispatcher(amqp)
	progressPublisher := providers.NewProgressPublisher(client, cfg)
	concurrencyGuard := providers.NewConcurrencyGuard(client, cfg)
	database := providers.NewMongoDatabase(connections)
	analysisRunRepository := repositories3.NewAnalysisRunRepository(database)
	decisionChainService := domain_services2.NewDecisionChainService(analysisRunRepository)
	policy := providers.NewAnalysisPolicy(cfg)
	analysisService := domain_services3.NewAnalysisService(taskRepository, taskDispatcher, progressPublisher, concurrencyGuard, decisionChainService, amqpBus, policy)
	operatorResolver := providers.NewAnalysisMCPOperator()
	tools := mcp_tools.NewTools(analysisService, operatorResolver)
	watchlistGroupRepository := repositories4.NewWatchlistGroupRepository(db)
	marketDataRepository := repositories5.NewMarketDataRepository(database)
	watchlistQuoteReader := providers.NewWatchlistQuoteReader(marketDataRepository)
	watchlistService := domain_services4.NewWatchlistService(watchlistGroupRepository, watchlistQuoteReader, amqpBus)
	mcp_toolsOperatorResolver := providers.NewWatchlistMCPOperator()
	mcp_toolsTools := mcp_tools2.NewTools(watchlistService, mcp_toolsOperatorResolver)
	screeningTemplateRepository := repositories6.NewScreeningTemplateRepository(db)
	stockScreener := repositories6.NewStockScreener(db, database)
	screeningService := domain_services5.NewScreeningService(screeningTemplateRepository, stockScreener, amqpBus)
	operatorResolver2 := providers.NewScreeningMCPOperator()
	tools2 := mcp_tools3.NewTools(screeningService, operatorResolver2)
	v := providers.NewMCPRegistrars(tools, mcp_toolsTools, tools2)
	mcpserverServer := mcpserver.New(authService, v, log)
	authHandler := http_handlers.NewAuthHandler(authService)
	userService := domain_services.NewUserService(userRepository, sessionRepository, bcryptHasher, amqpBus)
	userHandler := http_handlers.NewUserHandler(userService)
	stockRepository := repositories5.NewStockRepository(db)
	marketHTTPClient := providers.NewMarketHTTPClient(cfg)
	composite := providers.NewMarketDataProvider(cfg, marketHTTPClient, log)
	stockService := domain_services6.NewStockService(stockRepository, marketDataRepository, composite, amqpBus)
	stockHandler := http_handlers2.NewStockHandler(stockService)
	syncRunRepository := repositories5.NewSyncRunRepository(db)
	syncConfig := providers.NewSyncConfig(cfg)
	syncService := domain_services6.NewSyncService(stockRepository, marketDataRepository, syncRunRepository, composite, amqpBus, log, syncConfig)
	syncOperatorResolver := providers.NewStockOperator()
	syncHandler := http_handlers2.NewSyncHandler(syncService, syncOperatorResolver)
	llmhttpClient := providers.NewLLMHTTPClient(cfg)
	llmProviderRepository := repositories7.NewLLMProviderRepository(db)
	providerResolver := domain_services7.NewProviderResolver(llmProviderRepository)
	router := providers.NewLLMRouter(ctx, cfg, llmhttpClient, providerResolver, log)
	indicatorRepository := repositories3.NewIndicatorRepository(database)
	stockToolRegistry := domain_services2.NewStockToolRegistry(marketDataRepository, indicatorRepository)
	promptService := domain_services2.NewPromptService()
	completionCache := providers.NewCompletionCache(client)
	runtimeConfig := providers.NewRuntimeConfig()
	runtimeService := domain_services2.NewRuntimeService(router, stockToolRegistry, promptService, completionCache, runtimeConfig, log)
	evaluationRepository := repositories3.NewEvaluationRepository(database)
	engineConfig := providers.NewEngineConfig()
	engineService := domain_services2.NewEngineService(runtimeService, marketDataRepository, stockService, indicatorRepository, analysisRunRepository, evaluationRepository, amqpBus, log, engineConfig)
	agentHandler := http_handlers3.NewAgentHandler(engineService, evaluationRepository)
	batchRepository := repositories2.NewBatchRepository(db)
	batchService := domain_services3.NewBatchService(taskRepository, batchRepository, taskDispatcher, concurrencyGuard, amqpBus, policy)
	http_handlersOperatorResolver := providers.NewAnalysisOperator()
	analysisHandler := http_handlers4.NewAnalysisHandler(analysisService, batchService, http_handlersOperatorResolver)
	reportRepository := repositories8.NewReportRepository(db)
	analysisResultAdapter := providers.NewAnalysisResultAdapter(taskRepository)
	reportService := domain_services8.NewReportService(reportRepository, analysisResultAdapter, amqpBus)
	operatorResolver3 := providers.NewReportOperator()
	reportHandler := http_handlers5.NewReportHandler(reportService, operatorResolver3)
	scheduledJobRepository := repositories9.NewScheduledJobRepository(db)
	jobExecutionRepository := repositories9.NewJobExecutionRepository(db)
	jobDispatcher := repositories9.NewJobDispatcher(amqp)
	schedulerConfig := providers.NewSchedulerConfig()
	marketSyncRunner := providers.NewMarketSyncRunner(syncService)
	scheduledAnalysisRunner := providers.NewScheduledAnalysisRunner(analysisService)
	schedulerService := providers.NewSchedulerService(scheduledJobRepository, jobExecutionRepository, jobDispatcher, amqpBus, log, schedulerConfig, marketSyncRunner, scheduledAnalysisRunner)
	operatorResolver4 := providers.NewSchedulingOperator()
	scheduledJobHandler := http_handlers6.NewScheduledJobHandler(schedulerService, operatorResolver4)
	providerProbe := providers.NewProviderProbe(llmhttpClient)
	llmProviderService := domain_services7.NewLLMProviderService(llmProviderRepository, providerProbe, amqpBus)
	systemSettingRepository := repositories7.NewSystemSettingRepository(db)
	configService := domain_services7.NewConfigService(systemSettingRepository, llmProviderRepository, amqpBus)
	operatorResolver5 := providers.NewSystemOperator()
	configHandler := http_handlers7.NewConfigHandler(llmProviderService, configService, operatorResolver5)
	operatorResolver6 := providers.NewWatchlistOperator()
	watchlistHandler := http_handlers8.NewWatchlistHandler(watchlistService, operatorResolver6)
	paperAccountRepository := repositories10.NewPaperAccountRepository(db)
	paperQuoteReader := providers.NewPaperQuoteReader(marketDataRepository)
	paperTradingService := domain_services9.NewPaperTradingService(paperAccountRepository, paperQuoteReader, amqpBus)
	operatorResolver7 := providers.NewPaperOperator()
	paperTradingHandler := http_handlers9.NewPaperTradingHandler(paperTradingService, operatorResolver7)
	notificationRepository := repositories11.NewNotificationRepository(db)
	notificationService := domain_services10.NewNotificationService(notificationRepository)
	operatorResolver8 := providers.NewNotificationOperator()
	notificationHandler := http_handlers10.NewNotificationHandler(notificationService, operatorResolver8)
	operatorResolver9 := providers.NewScreeningOperator()
	screeningHandler := http_handlers11.NewScreeningHandler(screeningService, operatorResolver9)
	handlers := &server.Handlers{
		Auth:         authHandler,
		User:         userHandler,
		Stock:        stockHandler,
		Sync:         syncHandler,
		Agent:        agentHandler,
		Analysis:     analysisHandler,
		Report:       reportHandler,
		ScheduledJob: scheduledJobHandler,
		Config:       configHandler,
		Watchlist:    watchlistHandler,
		PaperTrading: paperTradingHandler,
		Notification: notificationHandler,
		Screening:    screeningHandler,
	}
	serverServer := server.New(cfg, log, authService, mcpserverServer, handlers)
	return serverServer, nil
}

// CreateUserService 只装配身份上下文，供启动期创建初始管理员使用。
//
// 单独开一个注入器而不是从 HTTP 那套里顺手拿：创建管理员发生在 HTTP 服务
// 启动**之前**，它不需要 LLM 路由，也不该因为消息队列连不上而失败。
func CreateUserService(ctx context.Context, cfg *config.Config, log *zap.Logger) (*domain_services.UserService, error) {
	connections, err := providers.NewSingletonConnections(ctx, cfg, log)
	if err != nil {
		return nil, err
	}
	db := providers.NewGormDB(connections)
	userRepository := repositories.NewUserRepository(db)
	client := providers.NewRedisClient(connections)
	sessionRepository := providers.NewSessionRepository(client, cfg)
	bcryptHasher := providers.NewPasswordHasher(cfg)
	amqp, err := providers.NewSingletonAmqp(cfg, log)
	if err != nil {
		return nil, err
	}
	amqpBus := providers.NewDomainEventBus(amqp, log)
	userService := domain_services.NewUserService(userRepository, sessionRepository, bcryptHasher, amqpBus)
	return userService, nil
}

// CreateAmqpHandlers 装配消息队列消费者。只有 worker 进程调用。
func CreateAmqpHandlers(ctx context.Context, cfg *config.Config, log *zap.Logger) (*event_handlers.AmqpHandlers, error) {
	amqp, err := providers.NewSingletonAmqp(cfg, log)
	if err != nil {
		return nil, err
	}
	connections, err := providers.NewSingletonConnections(ctx, cfg, log)
	if err != nil {
		return nil, err
	}
	db := providers.NewGormDB(connections)
	scheduledJobRepository := repositories9.NewScheduledJobRepository(db)
	jobExecutionRepository := repositories9.NewJobExecutionRepository(db)
	jobDispatcher := repositories9.NewJobDispatcher(amqp)
	amqpBus := providers.NewDomainEventBus(amqp, log)
	schedulerConfig := providers.NewSchedulerConfig()
	stockRepository := repositories5.NewStockRepository(db)
	database := providers.NewMongoDatabase(connections)
	marketDataRepository := repositories5.NewMarketDataRepository(database)
	syncRunRepository := repositories5.NewSyncRunRepository(db)
	marketHTTPClient := providers.NewMarketHTTPClient(cfg)
	composite := providers.NewMarketDataProvider(cfg, marketHTTPClient, log)
	syncConfig := providers.NewSyncConfig(cfg)
	syncService := domain_services6.NewSyncService(stockRepository, marketDataRepository, syncRunRepository, composite, amqpBus, log, syncConfig)
	marketSyncRunner := providers.NewMarketSyncRunner(syncService)
	taskRepository := repositories2.NewTaskRepository(db)
	taskDispatcher := providers.NewTaskDispatcher(amqp)
	client := providers.NewRedisClient(connections)
	progressPublisher := providers.NewProgressPublisher(client, cfg)
	concurrencyGuard := providers.NewConcurrencyGuard(client, cfg)
	analysisRunRepository := repositories3.NewAnalysisRunRepository(database)
	decisionChainService := domain_services2.NewDecisionChainService(analysisRunRepository)
	policy := providers.NewAnalysisPolicy(cfg)
	analysisService := domain_services3.NewAnalysisService(taskRepository, taskDispatcher, progressPublisher, concurrencyGuard, decisionChainService, amqpBus, policy)
	scheduledAnalysisRunner := providers.NewScheduledAnalysisRunner(analysisService)
	schedulerService := providers.NewSchedulerService(scheduledJobRepository, jobExecutionRepository, jobDispatcher, amqpBus, log, schedulerConfig, marketSyncRunner, scheduledAnalysisRunner)
	jobDueHandler := amqp_handlers.NewJobDueHandler(schedulerService, log)
	batchRepository := repositories2.NewBatchRepository(db)
	batchService := domain_services3.NewBatchService(taskRepository, batchRepository, taskDispatcher, concurrencyGuard, amqpBus, policy)
	llmhttpClient := providers.NewLLMHTTPClient(cfg)
	llmProviderRepository := repositories7.NewLLMProviderRepository(db)
	providerResolver := domain_services7.NewProviderResolver(llmProviderRepository)
	router := providers.NewLLMRouter(ctx, cfg, llmhttpClient, providerResolver, log)
	indicatorRepository := repositories3.NewIndicatorRepository(database)
	stockToolRegistry := domain_services2.NewStockToolRegistry(marketDataRepository, indicatorRepository)
	promptService := domain_services2.NewPromptService()
	completionCache := providers.NewCompletionCache(client)
	runtimeConfig := providers.NewRuntimeConfig()
	runtimeService := domain_services2.NewRuntimeService(router, stockToolRegistry, promptService, completionCache, runtimeConfig, log)
	stockService := domain_services6.NewStockService(stockRepository, marketDataRepository, composite, amqpBus)
	evaluationRepository := repositories3.NewEvaluationRepository(database)
	engineConfig := providers.NewEngineConfig()
	engineService := domain_services2.NewEngineService(runtimeService, marketDataRepository, stockService, indicatorRepository, analysisRunRepository, evaluationRepository, amqpBus, log, engineConfig)
	workerConfig := providers.NewAnalysisWorkerConfig(cfg)
	workerService := domain_services3.NewWorkerService(taskRepository, batchRepository, taskDispatcher, progressPublisher, concurrencyGuard, batchService, engineService, amqpBus, log, policy, workerConfig)
	taskDispatchHandler := amqp_handlers2.NewTaskDispatchHandler(workerService, log)
	amqpHandlers := event_handlers.NewAmqpHandlers(amqp, log, jobDueHandler, taskDispatchHandler)
	return amqpHandlers, nil
}

// CreateDomainEventHandlers 装配领域事件订阅者。只有 worker 进程调用。
func CreateDomainEventHandlers(ctx context.Context, cfg *config.Config, log *zap.Logger) (*event_handlers.DomainEventHandlers, error) {
	amqp, err := providers.NewSingletonAmqp(cfg, log)
	if err != nil {
		return nil, err
	}
	amqpBus := providers.NewDomainEventBus(amqp, log)
	connections, err := providers.NewSingletonConnections(ctx, cfg, log)
	if err != nil {
		return nil, err
	}
	db := providers.NewGormDB(connections)
	notificationRepository := repositories11.NewNotificationRepository(db)
	notificationService := domain_services10.NewNotificationService(notificationRepository)
	notificationSubscriber := domain_event_handlers.NewNotificationSubscriber(notificationService, log)
	reportRepository := repositories8.NewReportRepository(db)
	taskRepository := repositories2.NewTaskRepository(db)
	analysisResultAdapter := providers.NewAnalysisResultAdapter(taskRepository)
	reportService := domain_services8.NewReportService(reportRepository, analysisResultAdapter, amqpBus)
	onTaskCompletedHandler := domain_event_handlers2.NewOnTaskCompletedHandler(reportService)
	batchRepository := repositories2.NewBatchRepository(db)
	taskDispatcher := providers.NewTaskDispatcher(amqp)
	client := providers.NewRedisClient(connections)
	concurrencyGuard := providers.NewConcurrencyGuard(client, cfg)
	policy := providers.NewAnalysisPolicy(cfg)
	batchService := domain_services3.NewBatchService(taskRepository, batchRepository, taskDispatcher, concurrencyGuard, amqpBus, policy)
	batchSettlementHandler := domain_event_handlers3.NewBatchSettlementHandler(batchService)
	domainEventHandlers := event_handlers.NewDomainEventHandlers(amqp, amqpBus, log, notificationSubscriber, onTaskCompletedHandler, batchSettlementHandler)
	return domainEventHandlers, nil
}

// CreateWorkerRunners 装配 worker 的两个常驻循环。
func CreateWorkerRunners(ctx context.Context, cfg *config.Config, log *zap.Logger) (*providers.WorkerRunners, error) {
	connections, err := providers.NewSingletonConnections(ctx, cfg, log)
	if err != nil {
		return nil, err
	}
	db := providers.NewGormDB(connections)
	taskRepository := repositories2.NewTaskRepository(db)
	batchRepository := repositories2.NewBatchRepository(db)
	amqp, err := providers.NewSingletonAmqp(cfg, log)
	if err != nil {
		return nil, err
	}
	taskDispatcher := providers.NewTaskDispatcher(amqp)
	client := providers.NewRedisClient(connections)
	progressPublisher := providers.NewProgressPublisher(client, cfg)
	concurrencyGuard := providers.NewConcurrencyGuard(client, cfg)
	amqpBus := providers.NewDomainEventBus(amqp, log)
	policy := providers.NewAnalysisPolicy(cfg)
	batchService := domain_services3.NewBatchService(taskRepository, batchRepository, taskDispatcher, concurrencyGuard, amqpBus, policy)
	llmhttpClient := providers.NewLLMHTTPClient(cfg)
	llmProviderRepository := repositories7.NewLLMProviderRepository(db)
	providerResolver := domain_services7.NewProviderResolver(llmProviderRepository)
	router := providers.NewLLMRouter(ctx, cfg, llmhttpClient, providerResolver, log)
	database := providers.NewMongoDatabase(connections)
	marketDataRepository := repositories5.NewMarketDataRepository(database)
	indicatorRepository := repositories3.NewIndicatorRepository(database)
	stockToolRegistry := domain_services2.NewStockToolRegistry(marketDataRepository, indicatorRepository)
	promptService := domain_services2.NewPromptService()
	completionCache := providers.NewCompletionCache(client)
	runtimeConfig := providers.NewRuntimeConfig()
	runtimeService := domain_services2.NewRuntimeService(router, stockToolRegistry, promptService, completionCache, runtimeConfig, log)
	stockRepository := repositories5.NewStockRepository(db)
	marketHTTPClient := providers.NewMarketHTTPClient(cfg)
	composite := providers.NewMarketDataProvider(cfg, marketHTTPClient, log)
	stockService := domain_services6.NewStockService(stockRepository, marketDataRepository, composite, amqpBus)
	analysisRunRepository := repositories3.NewAnalysisRunRepository(database)
	evaluationRepository := repositories3.NewEvaluationRepository(database)
	engineConfig := providers.NewEngineConfig()
	engineService := domain_services2.NewEngineService(runtimeService, marketDataRepository, stockService, indicatorRepository, analysisRunRepository, evaluationRepository, amqpBus, log, engineConfig)
	workerConfig := providers.NewAnalysisWorkerConfig(cfg)
	workerService := domain_services3.NewWorkerService(taskRepository, batchRepository, taskDispatcher, progressPublisher, concurrencyGuard, batchService, engineService, amqpBus, log, policy, workerConfig)
	scheduledJobRepository := repositories9.NewScheduledJobRepository(db)
	jobExecutionRepository := repositories9.NewJobExecutionRepository(db)
	jobDispatcher := repositories9.NewJobDispatcher(amqp)
	schedulerConfig := providers.NewSchedulerConfig()
	syncRunRepository := repositories5.NewSyncRunRepository(db)
	syncConfig := providers.NewSyncConfig(cfg)
	syncService := domain_services6.NewSyncService(stockRepository, marketDataRepository, syncRunRepository, composite, amqpBus, log, syncConfig)
	marketSyncRunner := providers.NewMarketSyncRunner(syncService)
	decisionChainService := domain_services2.NewDecisionChainService(analysisRunRepository)
	analysisService := domain_services3.NewAnalysisService(taskRepository, taskDispatcher, progressPublisher, concurrencyGuard, decisionChainService, amqpBus, policy)
	scheduledAnalysisRunner := providers.NewScheduledAnalysisRunner(analysisService)
	schedulerService := providers.NewSchedulerService(scheduledJobRepository, jobExecutionRepository, jobDispatcher, amqpBus, log, schedulerConfig, marketSyncRunner, scheduledAnalysisRunner)
	workerRunners := providers.NewWorkerRunners(workerService, schedulerService, syncService)
	return workerRunners, nil
}

// CreateAnalysisEngine 装配一台可直接驱动的分析引擎，供 backfill 子命令使用。
//
// # 为什么回填不走任务队列
//
// 走 AnalysisService.Submit 看起来能白捡认领、重试与停滞巡检，但它有两个
// 对批量回填致命的性质：提交时要占一个 Redis 并发名额（PerUser / Global 上限），
// 因此几百条一次提交必然在中途被自己的限流挡住；而且那些名额与线上用户共用，
// 一次回填会把交互式提交的分析全部挤掉——回填是可以慢慢跑的，
// 有人正等着看的那次不行。
//
// 自己驱动则可以把节奏完全捏在手里：一次跑一格、可中断、可续跑，
// 而成本上限由 EngineConfig.MaxCostUSD 在引擎内部把关，不依赖调用方自律。
//
// 它复用 CoreSet 而不是手工装配：LLM 路由要先从数据库读出供应商配置才能解析模型名，
// 这类依赖顺序由 Wire 从函数签名推导，手写一份迟早和 serve 那边分叉。
func CreateBackfillDeps(ctx context.Context, cfg *config.Config, log *zap.Logger) (*providers.BackfillDeps, error) {
	llmhttpClient := providers.NewLLMHTTPClient(cfg)
	connections, err := providers.NewSingletonConnections(ctx, cfg, log)
	if err != nil {
		return nil, err
	}
	db := providers.NewGormDB(connections)
	llmProviderRepository := repositories7.NewLLMProviderRepository(db)
	providerResolver := domain_services7.NewProviderResolver(llmProviderRepository)
	router := providers.NewLLMRouter(ctx, cfg, llmhttpClient, providerResolver, log)
	database := providers.NewMongoDatabase(connections)
	marketDataRepository := repositories5.NewMarketDataRepository(database)
	indicatorRepository := repositories3.NewIndicatorRepository(database)
	stockToolRegistry := domain_services2.NewStockToolRegistry(marketDataRepository, indicatorRepository)
	promptService := domain_services2.NewPromptService()
	client := providers.NewRedisClient(connections)
	completionCache := providers.NewCompletionCache(client)
	runtimeConfig := providers.NewRuntimeConfig()
	runtimeService := domain_services2.NewRuntimeService(router, stockToolRegistry, promptService, completionCache, runtimeConfig, log)
	stockRepository := repositories5.NewStockRepository(db)
	marketHTTPClient := providers.NewMarketHTTPClient(cfg)
	composite := providers.NewMarketDataProvider(cfg, marketHTTPClient, log)
	amqp, err := providers.NewSingletonAmqp(cfg, log)
	if err != nil {
		return nil, err
	}
	amqpBus := providers.NewDomainEventBus(amqp, log)
	stockService := domain_services6.NewStockService(stockRepository, marketDataRepository, composite, amqpBus)
	analysisRunRepository := repositories3.NewAnalysisRunRepository(database)
	evaluationRepository := repositories3.NewEvaluationRepository(database)
	engineConfig := providers.NewEngineConfig()
	engineService := domain_services2.NewEngineService(runtimeService, marketDataRepository, stockService, indicatorRepository, analysisRunRepository, evaluationRepository, amqpBus, log, engineConfig)
	backfillDeps := providers.NewBackfillDeps(engineService, marketDataRepository, analysisRunRepository, connections)
	return backfillDeps, nil
}
