// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injectors

import (
	"context"
	"github.com/wt5858/trading-agents-go/config"
	http_handlers3 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/agent/application/http_handlers"
	domain_services4 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/agent/domain_services"
	repositories4 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/agent/repositories"
	amqp_handlers2 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/analysis/application/amqp_handlers"
	domain_event_handlers3 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/analysis/application/domain_event_handlers"
	http_handlers4 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/analysis/application/http_handlers"
	domain_services5 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/analysis/domain_services"
	repositories5 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/analysis/repositories"
	"github.com/wt5858/trading-agents-go/internal/bounded_contexts/identity/application/http_handlers"
	"github.com/wt5858/trading-agents-go/internal/bounded_contexts/identity/domain_services"
	"github.com/wt5858/trading-agents-go/internal/bounded_contexts/identity/repositories"
	"github.com/wt5858/trading-agents-go/internal/bounded_contexts/notification/application/domain_event_handlers"
	http_handlers10 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/notification/application/http_handlers"
	domain_services9 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/notification/domain_services"
	repositories10 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/notification/repositories"
	http_handlers9 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/paper_trading/application/http_handlers"
	domain_services8 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/paper_trading/domain_services"
	repositories9 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/paper_trading/repositories"
	domain_event_handlers2 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/report/application/domain_event_handlers"
	http_handlers5 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/report/application/http_handlers"
	domain_services6 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/report/domain_services"
	repositories6 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/report/repositories"
	"github.com/wt5858/trading-agents-go/internal/bounded_contexts/scheduling/application/amqp_handlers"
	http_handlers6 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/scheduling/application/http_handlers"
	repositories7 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/scheduling/repositories"
	http_handlers11 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/screening/application/http_handlers"
	domain_services10 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/screening/domain_services"
	repositories11 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/screening/repositories"
	http_handlers2 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/stock/application/http_handlers"
	domain_services2 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/stock/domain_services"
	repositories2 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/stock/repositories"
	http_handlers7 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/system_config/application/http_handlers"
	domain_services3 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/system_config/domain_services"
	repositories3 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/system_config/repositories"
	http_handlers8 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/watchlist/application/http_handlers"
	domain_services7 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/watchlist/domain_services"
	repositories8 "github.com/wt5858/trading-agents-go/internal/bounded_contexts/watchlist/repositories"
	"github.com/wt5858/trading-agents-go/internal/di/providers"
	"github.com/wt5858/trading-agents-go/internal/helpers/event_handlers"
	"github.com/wt5858/trading-agents-go/internal/server"
	"go.uber.org/zap"
)

// Injectors from container.go:

// CreateHTTPServer 装配 HTTP 服务。
//
// 它需要几乎全部上下文的领域服务（接口要暴露它们），但**不包含任何消费者**。
func CreateHTTPServer(ctx context.Context, cfg *config.Config, log *zap.Logger) (*server.Server, error) {
	connections, err := providers.NewSingletonConnections(ctx, cfg, log)
	if err != nil {
		return nil, err
	}
	db := providers.NewGormDB(connections)
	userRepository := repositories.NewUserRepository(db)
	client := providers.NewRedisClient(connections)
	sessionRepository := providers.NewSessionRepository(client, cfg)
	issuer := providers.NewTokenIssuer(cfg)
	bcryptHasher := providers.NewPasswordHasher(cfg)
	amqp, err := providers.NewSingletonAmqp(cfg, log)
	if err != nil {
		return nil, err
	}
	amqpBus := providers.NewDomainEventBus(amqp, log)
	authService := domain_services.NewAuthService(userRepository, sessionRepository, issuer, bcryptHasher, amqpBus)
	authHandler := http_handlers.NewAuthHandler(authService)
	userService := domain_services.NewUserService(userRepository, sessionRepository, bcryptHasher, amqpBus)
	userHandler := http_handlers.NewUserHandler(userService)
	stockRepository := repositories2.NewStockRepository(db)
	database := providers.NewMongoDatabase(connections)
	marketDataRepository := repositories2.NewMarketDataRepository(database)
	marketHTTPClient := providers.NewMarketHTTPClient(cfg)
	composite := providers.NewMarketDataProvider(cfg, marketHTTPClient, log)
	stockService := domain_services2.NewStockService(stockRepository, marketDataRepository, composite, amqpBus)
	stockHandler := http_handlers2.NewStockHandler(stockService)
	syncRunRepository := repositories2.NewSyncRunRepository(db)
	syncConfig := providers.NewSyncConfig(cfg)
	syncService := domain_services2.NewSyncService(stockRepository, marketDataRepository, syncRunRepository, composite, amqpBus, log, syncConfig)
	syncOperatorResolver := providers.NewStockOperator()
	syncHandler := http_handlers2.NewSyncHandler(syncService, syncOperatorResolver)
	llmhttpClient := providers.NewLLMHTTPClient(cfg)
	llmProviderRepository := repositories3.NewLLMProviderRepository(db)
	providerResolver := domain_services3.NewProviderResolver(llmProviderRepository)
	router := providers.NewLLMRouter(ctx, cfg, llmhttpClient, providerResolver, log)
	indicatorRepository := repositories4.NewIndicatorRepository(database)
	stockToolRegistry := domain_services4.NewStockToolRegistry(marketDataRepository, indicatorRepository)
	promptService := domain_services4.NewPromptService()
	runtimeConfig := providers.NewRuntimeConfig()
	runtimeService := domain_services4.NewRuntimeService(router, stockToolRegistry, promptService, runtimeConfig, log)
	engineConfig := providers.NewEngineConfig()
	engineService := domain_services4.NewEngineService(runtimeService, marketDataRepository, stockService, indicatorRepository, amqpBus, log, engineConfig)
	agentHandler := http_handlers3.NewAgentHandler(engineService)
	taskRepository := repositories5.NewTaskRepository(db)
	taskDispatcher := providers.NewTaskDispatcher(amqp)
	progressPublisher := providers.NewProgressPublisher(client, cfg)
	concurrencyGuard := providers.NewConcurrencyGuard(client, cfg)
	policy := providers.NewAnalysisPolicy(cfg)
	analysisService := domain_services5.NewAnalysisService(taskRepository, taskDispatcher, progressPublisher, concurrencyGuard, amqpBus, policy)
	batchRepository := repositories5.NewBatchRepository(db)
	batchService := domain_services5.NewBatchService(taskRepository, batchRepository, taskDispatcher, concurrencyGuard, amqpBus, policy)
	operatorResolver := providers.NewAnalysisOperator()
	analysisHandler := http_handlers4.NewAnalysisHandler(analysisService, batchService, operatorResolver)
	reportRepository := repositories6.NewReportRepository(db)
	analysisResultAdapter := providers.NewAnalysisResultAdapter(taskRepository)
	reportService := domain_services6.NewReportService(reportRepository, analysisResultAdapter, amqpBus)
	http_handlersOperatorResolver := providers.NewReportOperator()
	reportHandler := http_handlers5.NewReportHandler(reportService, http_handlersOperatorResolver)
	scheduledJobRepository := repositories7.NewScheduledJobRepository(db)
	jobExecutionRepository := repositories7.NewJobExecutionRepository(db)
	jobDispatcher := repositories7.NewJobDispatcher(amqp)
	schedulerConfig := providers.NewSchedulerConfig()
	marketSyncRunner := providers.NewMarketSyncRunner(syncService)
	scheduledAnalysisRunner := providers.NewScheduledAnalysisRunner(analysisService)
	schedulerService := providers.NewSchedulerService(scheduledJobRepository, jobExecutionRepository, jobDispatcher, amqpBus, log, schedulerConfig, marketSyncRunner, scheduledAnalysisRunner)
	operatorResolver2 := providers.NewSchedulingOperator()
	scheduledJobHandler := http_handlers6.NewScheduledJobHandler(schedulerService, operatorResolver2)
	providerProbe := providers.NewProviderProbe(llmhttpClient)
	llmProviderService := domain_services3.NewLLMProviderService(llmProviderRepository, providerProbe, amqpBus)
	systemSettingRepository := repositories3.NewSystemSettingRepository(db)
	configService := domain_services3.NewConfigService(systemSettingRepository, llmProviderRepository, amqpBus)
	operatorResolver3 := providers.NewSystemOperator()
	configHandler := http_handlers7.NewConfigHandler(llmProviderService, configService, operatorResolver3)
	watchlistGroupRepository := repositories8.NewWatchlistGroupRepository(db)
	watchlistQuoteReader := providers.NewWatchlistQuoteReader(marketDataRepository)
	watchlistService := domain_services7.NewWatchlistService(watchlistGroupRepository, watchlistQuoteReader, amqpBus)
	operatorResolver4 := providers.NewWatchlistOperator()
	watchlistHandler := http_handlers8.NewWatchlistHandler(watchlistService, operatorResolver4)
	paperAccountRepository := repositories9.NewPaperAccountRepository(db)
	paperQuoteReader := providers.NewPaperQuoteReader(marketDataRepository)
	paperTradingService := domain_services8.NewPaperTradingService(paperAccountRepository, paperQuoteReader, amqpBus)
	operatorResolver5 := providers.NewPaperOperator()
	paperTradingHandler := http_handlers9.NewPaperTradingHandler(paperTradingService, operatorResolver5)
	notificationRepository := repositories10.NewNotificationRepository(db)
	notificationService := domain_services9.NewNotificationService(notificationRepository)
	operatorResolver6 := providers.NewNotificationOperator()
	notificationHandler := http_handlers10.NewNotificationHandler(notificationService, operatorResolver6)
	screeningTemplateRepository := repositories11.NewScreeningTemplateRepository(db)
	stockScreener := repositories11.NewStockScreener(db, database)
	screeningService := domain_services10.NewScreeningService(screeningTemplateRepository, stockScreener, amqpBus)
	operatorResolver7 := providers.NewScreeningOperator()
	screeningHandler := http_handlers11.NewScreeningHandler(screeningService, operatorResolver7)
	handlers := &server.Handlers{
		Auth:         authHandler,
		User:         userHandler,
		Stock:        stockHandler,
		Sync:         syncHandler,
		Agent:        agentHandler,
		Analysis:     analysisHandler,
		Report:       reportHandler,
		ScheduledJob: scheduledJobHandler,
		Config:       configHandler,
		Watchlist:    watchlistHandler,
		PaperTrading: paperTradingHandler,
		Notification: notificationHandler,
		Screening:    screeningHandler,
	}
	serverServer := server.New(cfg, log, authService, handlers)
	return serverServer, nil
}

// CreateUserService 只装配身份上下文，供启动期创建初始管理员使用。
//
// 单独开一个注入器而不是从 HTTP 那套里顺手拿：创建管理员发生在 HTTP 服务
// 启动**之前**，它不需要 LLM 路由，也不该因为消息队列连不上而失败。
func CreateUserService(ctx context.Context, cfg *config.Config, log *zap.Logger) (*domain_services.UserService, error) {
	connections, err := providers.NewSingletonConnections(ctx, cfg, log)
	if err != nil {
		return nil, err
	}
	db := providers.NewGormDB(connections)
	userRepository := repositories.NewUserRepository(db)
	client := providers.NewRedisClient(connections)
	sessionRepository := providers.NewSessionRepository(client, cfg)
	bcryptHasher := providers.NewPasswordHasher(cfg)
	amqp, err := providers.NewSingletonAmqp(cfg, log)
	if err != nil {
		return nil, err
	}
	amqpBus := providers.NewDomainEventBus(amqp, log)
	userService := domain_services.NewUserService(userRepository, sessionRepository, bcryptHasher, amqpBus)
	return userService, nil
}

// CreateAmqpHandlers 装配消息队列消费者。只有 worker 进程调用。
func CreateAmqpHandlers(ctx context.Context, cfg *config.Config, log *zap.Logger) (*event_handlers.AmqpHandlers, error) {
	amqp, err := providers.NewSingletonAmqp(cfg, log)
	if err != nil {
		return nil, err
	}
	connections, err := providers.NewSingletonConnections(ctx, cfg, log)
	if err != nil {
		return nil, err
	}
	db := providers.NewGormDB(connections)
	scheduledJobRepository := repositories7.NewScheduledJobRepository(db)
	jobExecutionRepository := repositories7.NewJobExecutionRepository(db)
	jobDispatcher := repositories7.NewJobDispatcher(amqp)
	amqpBus := providers.NewDomainEventBus(amqp, log)
	schedulerConfig := providers.NewSchedulerConfig()
	stockRepository := repositories2.NewStockRepository(db)
	database := providers.NewMongoDatabase(connections)
	marketDataRepository := repositories2.NewMarketDataRepository(database)
	syncRunRepository := repositories2.NewSyncRunRepository(db)
	marketHTTPClient := providers.NewMarketHTTPClient(cfg)
	composite := providers.NewMarketDataProvider(cfg, marketHTTPClient, log)
	syncConfig := providers.NewSyncConfig(cfg)
	syncService := domain_services2.NewSyncService(stockRepository, marketDataRepository, syncRunRepository, composite, amqpBus, log, syncConfig)
	marketSyncRunner := providers.NewMarketSyncRunner(syncService)
	taskRepository := repositories5.NewTaskRepository(db)
	taskDispatcher := providers.NewTaskDispatcher(amqp)
	client := providers.NewRedisClient(connections)
	progressPublisher := providers.NewProgressPublisher(client, cfg)
	concurrencyGuard := providers.NewConcurrencyGuard(client, cfg)
	policy := providers.NewAnalysisPolicy(cfg)
	analysisService := domain_services5.NewAnalysisService(taskRepository, taskDispatcher, progressPublisher, concurrencyGuard, amqpBus, policy)
	scheduledAnalysisRunner := providers.NewScheduledAnalysisRunner(analysisService)
	schedulerService := providers.NewSchedulerService(scheduledJobRepository, jobExecutionRepository, jobDispatcher, amqpBus, log, schedulerConfig, marketSyncRunner, scheduledAnalysisRunner)
	jobDueHandler := amqp_handlers.NewJobDueHandler(schedulerService, log)
	batchRepository := repositories5.NewBatchRepository(db)
	batchService := domain_services5.NewBatchService(taskRepository, batchRepository, taskDispatcher, concurrencyGuard, amqpBus, policy)
	llmhttpClient := providers.NewLLMHTTPClient(cfg)
	llmProviderRepository := repositories3.NewLLMProviderRepository(db)
	providerResolver := domain_services3.NewProviderResolver(llmProviderRepository)
	router := providers.NewLLMRouter(ctx, cfg, llmhttpClient, providerResolver, log)
	indicatorRepository := repositories4.NewIndicatorRepository(database)
	stockToolRegistry := domain_services4.NewStockToolRegistry(marketDataRepository, indicatorRepository)
	promptService := domain_services4.NewPromptService()
	runtimeConfig := providers.NewRuntimeConfig()
	runtimeService := domain_services4.NewRuntimeService(router, stockToolRegistry, promptService, runtimeConfig, log)
	stockService := domain_services2.NewStockService(stockRepository, marketDataRepository, composite, amqpBus)
	engineConfig := providers.NewEngineConfig()
	engineService := domain_services4.NewEngineService(runtimeService, marketDataRepository, stockService, indicatorRepository, amqpBus, log, engineConfig)
	workerConfig := providers.NewAnalysisWorkerConfig(cfg)
	workerService := domain_services5.NewWorkerService(taskRepository, batchRepository, taskDispatcher, progressPublisher, concurrencyGuard, batchService, engineService, amqpBus, log, policy, workerConfig)
	taskDispatchHandler := amqp_handlers2.NewTaskDispatchHandler(workerService, log)
	amqpHandlers := event_handlers.NewAmqpHandlers(amqp, log, jobDueHandler, taskDispatchHandler)
	return amqpHandlers, nil
}

// CreateDomainEventHandlers 装配领域事件订阅者。只有 worker 进程调用。
func CreateDomainEventHandlers(ctx context.Context, cfg *config.Config, log *zap.Logger) (*event_handlers.DomainEventHandlers, error) {
	amqp, err := providers.NewSingletonAmqp(cfg, log)
	if err != nil {
		return nil, err
	}
	amqpBus := providers.NewDomainEventBus(amqp, log)
	connections, err := providers.NewSingletonConnections(ctx, cfg, log)
	if err != nil {
		return nil, err
	}
	db := providers.NewGormDB(connections)
	notificationRepository := repositories10.NewNotificationRepository(db)
	notificationService := domain_services9.NewNotificationService(notificationRepository)
	notificationSubscriber := domain_event_handlers.NewNotificationSubscriber(notificationService, log)
	reportRepository := repositories6.NewReportRepository(db)
	taskRepository := repositories5.NewTaskRepository(db)
	analysisResultAdapter := providers.NewAnalysisResultAdapter(taskRepository)
	reportService := domain_services6.NewReportService(reportRepository, analysisResultAdapter, amqpBus)
	onTaskCompletedHandler := domain_event_handlers2.NewOnTaskCompletedHandler(reportService)
	batchRepository := repositories5.NewBatchRepository(db)
	taskDispatcher := providers.NewTaskDispatcher(amqp)
	client := providers.NewRedisClient(connections)
	concurrencyGuard := providers.NewConcurrencyGuard(client, cfg)
	policy := providers.NewAnalysisPolicy(cfg)
	batchService := domain_services5.NewBatchService(taskRepository, batchRepository, taskDispatcher, concurrencyGuard, amqpBus, policy)
	batchSettlementHandler := domain_event_handlers3.NewBatchSettlementHandler(batchService)
	domainEventHandlers := event_handlers.NewDomainEventHandlers(amqp, amqpBus, log, notificationSubscriber, onTaskCompletedHandler, batchSettlementHandler)
	return domainEventHandlers, nil
}

// CreateWorkerRunners 装配 worker 的两个常驻循环。
func CreateWorkerRunners(ctx context.Context, cfg *config.Config, log *zap.Logger) (*providers.WorkerRunners, error) {
	connections, err := providers.NewSingletonConnections(ctx, cfg, log)
	if err != nil {
		return nil, err
	}
	db := providers.NewGormDB(connections)
	taskRepository := repositories5.NewTaskRepository(db)
	batchRepository := repositories5.NewBatchRepository(db)
	amqp, err := providers.NewSingletonAmqp(cfg, log)
	if err != nil {
		return nil, err
	}
	taskDispatcher := providers.NewTaskDispatcher(amqp)
	client := providers.NewRedisClient(connections)
	progressPublisher := providers.NewProgressPublisher(client, cfg)
	concurrencyGuard := providers.NewConcurrencyGuard(client, cfg)
	amqpBus := providers.NewDomainEventBus(amqp, log)
	policy := providers.NewAnalysisPolicy(cfg)
	batchService := domain_services5.NewBatchService(taskRepository, batchRepository, taskDispatcher, concurrencyGuard, amqpBus, policy)
	llmhttpClient := providers.NewLLMHTTPClient(cfg)
	llmProviderRepository := repositories3.NewLLMProviderRepository(db)
	providerResolver := domain_services3.NewProviderResolver(llmProviderRepository)
	router := providers.NewLLMRouter(ctx, cfg, llmhttpClient, providerResolver, log)
	database := providers.NewMongoDatabase(connections)
	marketDataRepository := repositories2.NewMarketDataRepository(database)
	indicatorRepository := repositories4.NewIndicatorRepository(database)
	stockToolRegistry := domain_services4.NewStockToolRegistry(marketDataRepository, indicatorRepository)
	promptService := domain_services4.NewPromptService()
	runtimeConfig := providers.NewRuntimeConfig()
	runtimeService := domain_services4.NewRuntimeService(router, stockToolRegistry, promptService, runtimeConfig, log)
	stockRepository := repositories2.NewStockRepository(db)
	marketHTTPClient := providers.NewMarketHTTPClient(cfg)
	composite := providers.NewMarketDataProvider(cfg, marketHTTPClient, log)
	stockService := domain_services2.NewStockService(stockRepository, marketDataRepository, composite, amqpBus)
	engineConfig := providers.NewEngineConfig()
	engineService := domain_services4.NewEngineService(runtimeService, marketDataRepository, stockService, indicatorRepository, amqpBus, log, engineConfig)
	workerConfig := providers.NewAnalysisWorkerConfig(cfg)
	workerService := domain_services5.NewWorkerService(taskRepository, batchRepository, taskDispatcher, progressPublisher, concurrencyGuard, batchService, engineService, amqpBus, log, policy, workerConfig)
	scheduledJobRepository := repositories7.NewScheduledJobRepository(db)
	jobExecutionRepository := repositories7.NewJobExecutionRepository(db)
	jobDispatcher := repositories7.NewJobDispatcher(amqp)
	schedulerConfig := providers.NewSchedulerConfig()
	syncRunRepository := repositories2.NewSyncRunRepository(db)
	syncConfig := providers.NewSyncConfig(cfg)
	syncService := domain_services2.NewSyncService(stockRepository, marketDataRepository, syncRunRepository, composite, amqpBus, log, syncConfig)
	marketSyncRunner := providers.NewMarketSyncRunner(syncService)
	analysisService := domain_services5.NewAnalysisService(taskRepository, taskDispatcher, progressPublisher, concurrencyGuard, amqpBus, policy)
	scheduledAnalysisRunner := providers.NewScheduledAnalysisRunner(analysisService)
	schedulerService := providers.NewSchedulerService(scheduledJobRepository, jobExecutionRepository, jobDispatcher, amqpBus, log, schedulerConfig, marketSyncRunner, scheduledAnalysisRunner)
	workerRunners := providers.NewWorkerRunners(workerService, schedulerService, syncService)
	return workerRunners, nil
}
